name: "Scan secrets"
description: "Scan secrets"
runs:
  using: "composite"
  steps:
    - name: "Scan secrets"
      shell: bash
      run: |
<<<<<<< HEAD
        export ALL_FILES=true # Do not change this line, as new patterns may be added or history may be rewritten
        ./scripts/githooks/scan-secrets.sh
=======
        # Please do not change this `check=whole-history` setting, as new patterns may be added or history may be rewritten.
        check=whole-history ./scripts/githooks/scan-secrets.sh
>>>>>>> 15499cbbd2aae9db59fb34ff8b5abf070066fbef
